/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package software;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ASUS
 */
public class Customer_SignUp extends javax.swing.JFrame {

    /**
     * Creates new form Customer_SignUp
     */
    public Customer_SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Name_TF = new javax.swing.JTextField();
        Email_TF = new javax.swing.JTextField();
        Phone_TF = new javax.swing.JTextField();
        Id_TF = new javax.swing.JTextField();
        Pass_TF = new javax.swing.JTextField();
        ConfPass_TF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Login_Panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        CreateAccount_Panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Poor Richard", 1, 40)); // NOI18N
        jLabel1.setText("Sign Up");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        Name_TF.setBackground(new java.awt.Color(0, 0, 0));
        Name_TF.setFont(new java.awt.Font("Poor Richard", 1, 36)); // NOI18N
        Name_TF.setForeground(new java.awt.Color(51, 51, 51));
        Name_TF.setText("Enter Full Name:");
        Name_TF.setFocusable(false);
        Name_TF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Name_TFMouseClicked(evt);
            }
        });
        Name_TF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Name_TFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Name_TFFocusLost(evt);
            }
        });

        Email_TF.setBackground(new java.awt.Color(0, 0, 0));
        Email_TF.setFont(new java.awt.Font("Poor Richard", 1, 36)); // NOI18N
        Email_TF.setForeground(new java.awt.Color(51, 51, 51));
        Email_TF.setText("Enter E-mail Id:");
        Email_TF.setFocusable(false);
        Email_TF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Email_TFMouseClicked(evt);
            }
        });
        Email_TF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Email_TFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Email_TFFocusLost(evt);
            }
        });

        Phone_TF.setBackground(new java.awt.Color(0, 0, 0));
        Phone_TF.setFont(new java.awt.Font("Poor Richard", 1, 36)); // NOI18N
        Phone_TF.setForeground(new java.awt.Color(51, 51, 51));
        Phone_TF.setText("Enter Phone Number:");
        Phone_TF.setFocusable(false);
        Phone_TF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Phone_TFMouseClicked(evt);
            }
        });
        Phone_TF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Phone_TFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Phone_TFFocusLost(evt);
            }
        });

        Id_TF.setBackground(new java.awt.Color(0, 0, 0));
        Id_TF.setFont(new java.awt.Font("Poor Richard", 1, 36)); // NOI18N
        Id_TF.setForeground(new java.awt.Color(51, 51, 51));
        Id_TF.setText("Create User Id:");
        Id_TF.setFocusable(false);
        Id_TF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Id_TFMouseClicked(evt);
            }
        });
        Id_TF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Id_TFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Id_TFFocusLost(evt);
            }
        });

        Pass_TF.setBackground(new java.awt.Color(0, 0, 0));
        Pass_TF.setFont(new java.awt.Font("Poor Richard", 1, 36)); // NOI18N
        Pass_TF.setForeground(new java.awt.Color(51, 51, 51));
        Pass_TF.setText("Create Password:");
        Pass_TF.setFocusable(false);
        Pass_TF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pass_TFMouseClicked(evt);
            }
        });
        Pass_TF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Pass_TFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Pass_TFFocusLost(evt);
            }
        });

        ConfPass_TF.setBackground(new java.awt.Color(0, 0, 0));
        ConfPass_TF.setFont(new java.awt.Font("Poor Richard", 1, 36)); // NOI18N
        ConfPass_TF.setForeground(new java.awt.Color(51, 51, 51));
        ConfPass_TF.setText("Confirm Password:");
        ConfPass_TF.setFocusable(false);
        ConfPass_TF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConfPass_TFMouseClicked(evt);
            }
        });
        ConfPass_TF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ConfPass_TFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ConfPass_TFFocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Poor Richard", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Already have an Account ? ");

        Login_Panel.setBackground(new java.awt.Color(0, 0, 0));
        Login_Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Login_PanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Login_PanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Login_PanelMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Poor Richard", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Login");

        javax.swing.GroupLayout Login_PanelLayout = new javax.swing.GroupLayout(Login_Panel);
        Login_Panel.setLayout(Login_PanelLayout);
        Login_PanelLayout.setHorizontalGroup(
            Login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 91, Short.MAX_VALUE)
            .addGroup(Login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Login_PanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        Login_PanelLayout.setVerticalGroup(
            Login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
            .addGroup(Login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Login_PanelLayout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(10, 10, 10)))
        );

        CreateAccount_Panel.setBackground(new java.awt.Color(0, 0, 0));
        CreateAccount_Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CreateAccount_PanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CreateAccount_PanelMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Poor Richard", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Create Account");
        jLabel3.setToolTipText("click to create account");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout CreateAccount_PanelLayout = new javax.swing.GroupLayout(CreateAccount_Panel);
        CreateAccount_Panel.setLayout(CreateAccount_PanelLayout);
        CreateAccount_PanelLayout.setHorizontalGroup(
            CreateAccount_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
        );
        CreateAccount_PanelLayout.setVerticalGroup(
            CreateAccount_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Name_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Email_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Phone_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Id_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pass_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConfPass_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(Login_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CreateAccount_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Name_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(Email_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(Phone_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(Id_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(Pass_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(ConfPass_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(CreateAccount_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Login_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Name_TFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Name_TFFocusGained
        // TODO add your handling code here:
        if(Name_TF.getText().equals("Enter Full Name:"))
        {
            Name_TF.setText("");
            Name_TF.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_Name_TFFocusGained

    private void Name_TFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Name_TFFocusLost
        // TODO add your handling code here:
        if(Name_TF.getText().equals(""))
        {
            Name_TF.setText("Enter Full Name:");
            Name_TF.setForeground(new Color(51,51,51));
        }
    }//GEN-LAST:event_Name_TFFocusLost

    private void Email_TFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Email_TFFocusGained
        // TODO add your handling code here:
        if(Email_TF.getText().equals("Enter E-mail Id:"))
        {
            Email_TF.setText("");
            Email_TF.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_Email_TFFocusGained

    private void Email_TFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Email_TFFocusLost
        // TODO add your handling code here:
         if(Email_TF.getText().equals(""))
        {
            Email_TF.setText("Enter E-mail Id:");
            Email_TF.setForeground(new Color(51,51,51));
        }
    }//GEN-LAST:event_Email_TFFocusLost

    private void Phone_TFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Phone_TFFocusGained
        // TODO add your handling code here:
        if(Phone_TF.getText().equals("Enter Phone Number:"))
        {
            Phone_TF.setText("");
            Phone_TF.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_Phone_TFFocusGained

    private void Phone_TFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Phone_TFFocusLost
        // TODO add your handling code here:
        if(Phone_TF.getText().equals(""))
        {
            Phone_TF.setText("Enter Phone Number:");
            Phone_TF.setForeground(new Color(51,51,51));
        }
    }//GEN-LAST:event_Phone_TFFocusLost

    private void Id_TFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Id_TFFocusGained
        // TODO add your handling code here:
        if(Id_TF.getText().equals("Create User Id:"))
        {
            Id_TF.setText("");
            Id_TF.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_Id_TFFocusGained

    private void Id_TFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Id_TFFocusLost
        // TODO add your handling code here:
         if(Id_TF.getText().equals(""))
        {
            Id_TF.setText("Create User Id:");
            Id_TF.setForeground(new Color(51,51,51));
        }
    }//GEN-LAST:event_Id_TFFocusLost

    private void Pass_TFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Pass_TFFocusGained
        // TODO add your handling code here:
        if(Pass_TF.getText().equals("Create Password:"))
        {
            Pass_TF.setText("");
            Pass_TF.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_Pass_TFFocusGained

    private void Pass_TFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Pass_TFFocusLost
        // TODO add your handling code here:
        if(Pass_TF.getText().equals(""))
        {
            Pass_TF.setText("Create Password:");
            Pass_TF.setForeground(new Color(51,51,51));
        }
    }//GEN-LAST:event_Pass_TFFocusLost

    private void ConfPass_TFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ConfPass_TFFocusGained
        // TODO add your handling code here:
        if(ConfPass_TF.getText().equals("Confirm Password:"))
        {
            ConfPass_TF.setText("");
            ConfPass_TF.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_ConfPass_TFFocusGained

    private void ConfPass_TFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ConfPass_TFFocusLost
        // TODO add your handling code here:
        if(ConfPass_TF.getText().equals(""))
        {
            ConfPass_TF.setText("Confirm Password:");
            ConfPass_TF.setForeground(new Color(51,51,51));
        }
    }//GEN-LAST:event_ConfPass_TFFocusLost

    private void Login_PanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Login_PanelMouseEntered
        // TODO add your handling code here:
        setColor(Login_Panel);
    }//GEN-LAST:event_Login_PanelMouseEntered

    private void Login_PanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Login_PanelMouseExited
        // TODO add your handling code here:
        resetColor(Login_Panel);
    }//GEN-LAST:event_Login_PanelMouseExited

    private void CreateAccount_PanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateAccount_PanelMouseEntered
        // TODO add your handling code here:
        setColor(CreateAccount_Panel);
    }//GEN-LAST:event_CreateAccount_PanelMouseEntered

    private void CreateAccount_PanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateAccount_PanelMouseExited
        // TODO add your handling code here:
        resetColor(CreateAccount_Panel);
    }//GEN-LAST:event_CreateAccount_PanelMouseExited

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
         try{
        /*String url = "jdbc:mysql://sql6.freesqldatabase.com:3306/";
String dbName = "sql6443034";
String driver = "com.mysql.cj.jdbc.Driver";
String userName = "sql6443034"; 
String password = "uuSPu7mjFg"; 
    Class.forName(driver).newInstance();
    Connection con = DriverManager.getConnection(url+dbName,userName,password);*/
        
    Class.forName("java.sql.Driver");
           Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/carservice","root","admin");
           Statement stmt=conn.createStatement();
        String User_name=Name_TF.getText();
        String email_id=Email_TF.getText();
        String phone=Phone_TF.getText();
        String u_Id=Id_TF.getText();
        String password1=Pass_TF.getText();
        String password2=ConfPass_TF.getText();
        
        String sql="insert into customer values('"+u_Id+"','"+User_name+"','"+email_id+"','"+phone+"','"+password2+"')";
        /*if(password1.equals(password2))
        {
            JOptionPane.showMessageDialog(this, "Same Passwords");
        }*/
        if(password1.equals(password2))
        {     
        int rs=stmt.executeUpdate(sql);
            if(rs==1){
            JOptionPane.showMessageDialog(this, "Account Created!");
            Thread.sleep(3000);
            dispose();
            Customer_Login obj=new Customer_Login();
            obj.show();
        }
            else{
            JOptionPane.showMessageDialog(this, "This User ID is already taken...\nTry different User ID");
            //Name_TF.setText("");
            //Email_TF.setText("");
            //Phone_TF.setText("");
            Id_TF.setText("");
            //Pass_TF.setText("");
            //ConfPass_TF.setText("");
        }
        }
        else{
            JOptionPane.showMessageDialog(this, "Password and Confirm password don't match");
        }
        conn.close();
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void Login_PanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Login_PanelMouseClicked
        // TODO add your handling code here:
        dispose();
        Customer_Login obj=new Customer_Login();
        obj.show();
    }//GEN-LAST:event_Login_PanelMouseClicked

    private void Name_TFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Name_TFMouseClicked
        // TODO add your handling code here:
        Name_TF.setFocusable(true);
    }//GEN-LAST:event_Name_TFMouseClicked

    private void Email_TFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Email_TFMouseClicked
        // TODO add your handling code here:
        Email_TF.setFocusable(true);
    }//GEN-LAST:event_Email_TFMouseClicked

    private void Phone_TFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Phone_TFMouseClicked
        // TODO add your handling code here:
        Phone_TF.setFocusable(true);
    }//GEN-LAST:event_Phone_TFMouseClicked

    private void Id_TFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Id_TFMouseClicked
        // TODO add your handling code here:
        Id_TF.setFocusable(true);
    }//GEN-LAST:event_Id_TFMouseClicked

    private void Pass_TFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pass_TFMouseClicked
        // TODO add your handling code here:
        Pass_TF.setFocusable(true);
    }//GEN-LAST:event_Pass_TFMouseClicked

    private void ConfPass_TFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfPass_TFMouseClicked
        // TODO add your handling code here:
        ConfPass_TF.setFocusable(true);
    }//GEN-LAST:event_ConfPass_TFMouseClicked

    void setColor(JPanel panel)
    {
        panel.setBackground(new Color(30,30,30));
    }
    
    void resetColor(JPanel panel)
    {
        panel.setBackground(new Color(0,0,0));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer_SignUp().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ConfPass_TF;
    private javax.swing.JPanel CreateAccount_Panel;
    private javax.swing.JTextField Email_TF;
    private javax.swing.JTextField Id_TF;
    private javax.swing.JPanel Login_Panel;
    private javax.swing.JTextField Name_TF;
    private javax.swing.JTextField Pass_TF;
    private javax.swing.JTextField Phone_TF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
