/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package software;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ASUS
 */
public class Customer_Login extends javax.swing.JFrame {

    /**
     * Creates new form Customer_Login
     */
    public Customer_Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Sign_Up = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        UserId_TF = new javax.swing.JTextField();
        Password_TF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(742, 481));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Poor Richard", 1, 40)); // NOI18N
        jLabel1.setText("Login");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(315, 315, 315)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Poor Richard", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Don't have an Account ? ");

        Sign_Up.setBackground(new java.awt.Color(0, 0, 0));
        Sign_Up.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sign_UpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Sign_UpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Sign_UpMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Poor Richard", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Sign Up");

        javax.swing.GroupLayout Sign_UpLayout = new javax.swing.GroupLayout(Sign_Up);
        Sign_Up.setLayout(Sign_UpLayout);
        Sign_UpLayout.setHorizontalGroup(
            Sign_UpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Sign_UpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        Sign_UpLayout.setVerticalGroup(
            Sign_UpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Sign_UpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/software/icons8_forward_30px.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/software/icons8_back_30px_1.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        UserId_TF.setBackground(new java.awt.Color(0, 0, 0));
        UserId_TF.setFont(new java.awt.Font("Poor Richard", 1, 36)); // NOI18N
        UserId_TF.setForeground(new java.awt.Color(51, 51, 51));
        UserId_TF.setText("Enter User Id:");
        UserId_TF.setFocusable(false);
        UserId_TF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserId_TFMouseClicked(evt);
            }
        });
        UserId_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserId_TFActionPerformed(evt);
            }
        });
        UserId_TF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UserId_TFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                UserId_TFFocusLost(evt);
            }
        });

        Password_TF.setBackground(new java.awt.Color(0, 0, 0));
        Password_TF.setFont(new java.awt.Font("Poor Richard", 1, 36)); // NOI18N
        Password_TF.setForeground(new java.awt.Color(51, 51, 51));
        Password_TF.setText("Enter Password:");
        Password_TF.setFocusable(false);
        Password_TF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Password_TFMouseClicked(evt);
            }
        });
        Password_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password_TFActionPerformed(evt);
            }
        });
        Password_TF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Password_TFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Password_TFFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UserId_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(Sign_Up, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Password_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(66, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(25, 25, 25))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(UserId_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(Password_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Sign_Up, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Sign_UpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sign_UpMouseEntered
        setColor(Sign_Up);
    }//GEN-LAST:event_Sign_UpMouseEntered

    private void Sign_UpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sign_UpMouseExited
        resetColor(Sign_Up);
    }//GEN-LAST:event_Sign_UpMouseExited

    private void UserId_TFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UserId_TFFocusGained
        // TODO add your handling code here:
        if(UserId_TF.getText().equals("Enter User Id:"))
        {
            UserId_TF.setText("");
            UserId_TF.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_UserId_TFFocusGained

    private void UserId_TFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UserId_TFFocusLost
        // TODO add your handling code here:
        if(UserId_TF.getText().equals(""))
        {
            UserId_TF.setText("Enter User Id:");
            UserId_TF.setForeground(new Color(51,51,51));
        }
    }//GEN-LAST:event_UserId_TFFocusLost

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        
    }//GEN-LAST:event_jPanel1MouseClicked

    private void UserId_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserId_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserId_TFActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        
            //change detail when database is finalize
        /*String url = "jdbc:mysql://sql6.freesqldatabase.com:3306/";
        String dbName = "sql6443034";
        String driver = "com.mysql.cj.jdbc.Driver";
        String userName = "sql6443034"; 
        String password = "uuSPu7mjFg"; */
          try{
              Class.forName("java.sql.Driver");
           Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/carservice","root","admin");
           Statement stmt=conn.createStatement();
    
        String Cust_Id=UserId_TF.getText();
        String pass=Password_TF.getText();
        String sql="select Cust_Id,password from customer where Cust_Id='"+Cust_Id+"' and password='"+pass+"';";
        ResultSet rs=stmt.executeQuery(sql);
        if(rs.next())
        {
            new MAIN(Cust_Id).setVisible(true);
                dispose();
        }
        else{
            JOptionPane.showMessageDialog(this, "Username or Password Invalid!");
               
        }
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        dispose();
        Open obj=new Open();
        obj.show();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void Sign_UpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sign_UpMouseClicked
               // TODO add your handling code here:
        dispose();
        Customer_SignUp obj3=new Customer_SignUp();
        obj3.show();
    }//GEN-LAST:event_Sign_UpMouseClicked

    private void Password_TFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Password_TFFocusLost
        // TODO add your handling code here:
        if(Password_TF.getText().equals(""))
        {
            Password_TF.setText("Enter Password:");
            Password_TF.setForeground(new Color(51,51,51));
        }
    }//GEN-LAST:event_Password_TFFocusLost

    private void Password_TFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Password_TFFocusGained
        // TODO add your handling code here:
        if(Password_TF.getText().equals("Enter Password:"))
        {
            Password_TF.setText("");
            Password_TF.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_Password_TFFocusGained

    private void Password_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Password_TFActionPerformed

    private void UserId_TFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserId_TFMouseClicked
        // TODO add your handling code here:
        UserId_TF.setFocusable(true);
    }//GEN-LAST:event_UserId_TFMouseClicked

    private void Password_TFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Password_TFMouseClicked
        // TODO add your handling code here:
        Password_TF.setFocusable(true);
    }//GEN-LAST:event_Password_TFMouseClicked

    void setColor(JPanel panel)
    {
        panel.setBackground(new Color(30,30,30));
    }
    
    void resetColor(JPanel panel)
    {
        panel.setBackground(new Color(0,0,0));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer_Login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Password_TF;
    private javax.swing.JPanel Sign_Up;
    private javax.swing.JTextField UserId_TF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
