/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package software;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author ASUS
 */
public class Open extends javax.swing.JFrame {

    /**
     * Creates new form Open
     */
    public Open() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Customer_Panel = new javax.swing.JPanel();
        Employee_Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Customer_Panel.setBackground(new java.awt.Color(0, 0, 0));
        Customer_Panel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Customer_PanelMouseMoved(evt);
            }
        });
        Customer_Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Customer_PanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Customer_PanelMouseExited(evt);
            }
        });

        Employee_Panel.setBackground(new java.awt.Color(51, 51, 51));
        Employee_Panel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Employee_PanelMouseMoved(evt);
            }
        });
        Employee_Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Employee_PanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Employee_PanelMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Poor Richard", 1, 36)); // NOI18N
        jLabel1.setText("I AM AN EMPLOYEE");

        javax.swing.GroupLayout Employee_PanelLayout = new javax.swing.GroupLayout(Employee_Panel);
        Employee_Panel.setLayout(Employee_PanelLayout);
        Employee_PanelLayout.setHorizontalGroup(
            Employee_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Employee_PanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        Employee_PanelLayout.setVerticalGroup(
            Employee_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Employee_PanelLayout.createSequentialGroup()
                .addContainerGap(337, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );

        jLabel2.setFont(new java.awt.Font("Poor Richard", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("I AM A CUSTOMER");

        javax.swing.GroupLayout Customer_PanelLayout = new javax.swing.GroupLayout(Customer_Panel);
        Customer_Panel.setLayout(Customer_PanelLayout);
        Customer_PanelLayout.setHorizontalGroup(
            Customer_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Customer_PanelLayout.createSequentialGroup()
                .addComponent(Employee_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addGap(0, 27, Short.MAX_VALUE))
        );
        Customer_PanelLayout.setVerticalGroup(
            Customer_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Employee_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Customer_PanelLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Customer_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Customer_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Employee_PanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Employee_PanelMouseMoved
        setColor1(Customer_Panel);
        resetColor2(Employee_Panel);
    }//GEN-LAST:event_Employee_PanelMouseMoved

    private void Customer_PanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Customer_PanelMouseMoved
        setColor2(Employee_Panel);
        resetColor1(Customer_Panel);
        
    }//GEN-LAST:event_Customer_PanelMouseMoved

    private void Employee_PanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Employee_PanelMouseExited
        setColor2(Customer_Panel);
    }//GEN-LAST:event_Employee_PanelMouseExited

    private void Customer_PanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Customer_PanelMouseExited
        setColor1(Employee_Panel);
    }//GEN-LAST:event_Customer_PanelMouseExited

    private void Customer_PanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Customer_PanelMouseClicked
       dispose();
       Customer_Login obj1=new Customer_Login();
       obj1.show();
    }//GEN-LAST:event_Customer_PanelMouseClicked

    private void Employee_PanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Employee_PanelMouseClicked
        dispose();
        Employee_Login obj2=new Employee_Login();
        obj2.show();
    }//GEN-LAST:event_Employee_PanelMouseClicked

    void setColor1(JPanel panel)
    {
        panel.setBackground(new Color(51,51,51));
    }
    
    void resetColor1(JPanel panel)
    {
        panel.setBackground(new Color(0,0,0));
    }
    void setColor2(JPanel panel)
    {
        panel.setBackground(new Color(0,0,0));
    }
    
    void resetColor2(JPanel panel)
    {
        panel.setBackground(new Color(51,51,51));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Open.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Open.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Open.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Open.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Open().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Customer_Panel;
    private javax.swing.JPanel Employee_Panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
